name: lint_python
on: [push, pull_request]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --ignore=E126,E203,E401,E711,E712,E722,E731,E741,F401,F841,W291,W503,W605 \
               --count --max-complexity=62 --max-line-length=3266 --show-source --statistics
